### ISSUE TITLE
Details on firmware used

### ISSUE THREAD

**Issue by knedlsepp** [joseph-long/pixie#1]
Could you maybe provide some insights on what firmware was needed to get this working. I'm currently using mrchromebox firmware. I've wanted to make this work for a long time but was never successful, so I would be thrilled to apply your configuration and finally have audio on my machine again.😃

**Comment by knedlsepp** [comment]
With my current setup: https://github.com/knedlsepp/flakebook/commit/77f0f4da9a676527bd6241feb27864e1107f8e88, I get this output from dmesg: https://gist.github.com/ba001bf4e436d7b386c853bad4b607ca

**Comment by knedlsepp** [comment]
Did now try both stock firmware and mr chromebox RW_LEGACY with your configuration.
I did have to disable systemd-boot however:
```patch
diff --git a/configuration.nix b/configuration.nix
index 5fcf841..60026b1 100755
--- a/configuration.nix
+++ b/configuration.nix
@@ -13,14 +13,15 @@
       ./cave-audio.nix
     ];
 
+  boot.kernelPackages = pkgs.linuxPackages_latest;
   # --- Use the GRUB 2 boot loader + legacy boot (for dual-boot with ChromeOS)
-  # boot.loader.grub.enable = true;
-  # boot.loader.grub.version = 2;
-  # boot.loader.grub.device = "/dev/mmcblk0"; # or "nodev" for efi only
+  boot.loader.grub.enable = true;
+  boot.loader.grub.version = 2;
+  boot.loader.grub.device = "/dev/mmcblk0"; # or "nodev" for efi only
   # boot.loader.grub.forceInstall = true;
   # --- Use EFI boot with systemd-boot (after full firmware replacement)
-  boot.loader.systemd-boot.enable = true;
-  boot.loader.efi.canTouchEfiVariables = true;
+  # boot.loader.systemd-boot.enable = true;
+  # boot.loader.efi.canTouchEfiVariables = true;
```
Still don't have working audio: https://gist.github.com/b19f99c0a1fbb6fc3bfec3099186dbc4 but "Speaker" and "Internal mic" show up in the audio config.

**Comment by knedlsepp** [comment]
Finally got a working setup using:
- RW_LEGACY
- `nix-channel --add https://nixos.org/channels/nixos-19.03 nixos`

https://gist.github.com/knedlsepp/1228a70699e4b6991ca3b31ecbdd9859
However there is still a noticable pop when beginning to play some audio.

**Comment by knedlsepp** [comment]
With legacy boot I'm having trouble hibernating but have working audio. With EFI boot I can have hibernation, but no audio. Could you get both working with your setup?

**Comment by joseph-long** [comment]
Hello! I apologize for not seeing this sooner. I toggled some setting in GitHub and stopped getting notifications for any new repositories I made.

Sad to report that NixOS is not currently on my C302CA, since some subtle incompatibility buried deep in `conda`'s installer made it unusable as a work OS for me. I do have EFI boot and audio with my particular Kubuntu setup right now, though I do not recall if deep sleep / hibernation is working.

The key ingredients are, as far as I can tell:

  - a new enough Linux kernel to have the backwards-compatibility fixes to ALSA topology parsing
  - the topology file from ChromeOS (or the kernel bugzilla attachments :eyes:)
  - fw_dsp_release.bin -> fw_dsp_release_v969.bin

Best of luck! Now that [this issue](https://github.com/ContinuumIO/anaconda-issues/issues/11159#issuecomment-533661891) is fixed I plan to switch back to NixOS at some point. I have problems with stalling in Kubuntu that I can't track down, which might in fact be problems with stalling in vanilla Linux in general that I just never noticed until I tried using the laptop for real work.

**Comment by knedlsepp** [comment]
Thx for getting back to me. I'll try again to make things work using EFI boot as you state it should be doable.
As for conda on NixOS. Sadly that's not a very well supported use case, however somebody patched the conda installer to make it installable via nix and make it somewhat usable. See for example the instructions here: https://nixos.wiki/wiki/Python I don't think it will behave correctly as in every other distro, but it's a start.

**Comment by joseph-long** [comment]
One ingredient I forgot, but you’re probably already using: the ALSA UCM configs from https://github.com/nebulakl/cave-audio or galliumos-skylake

**Comment by joseph-long** [comment]
I also wrote a blog post, but it's more Kubuntu than NixOS. Forgot to publish it until now, but in case it's useful: https://joseph-long.com/writing/chromebook-linux-adventure/

**Comment by joseph-long** [comment]
With the commit I just pushed, I was able to load the topology and (after doing `alsaucm -c sklnau8825max set _verb Speaker` and adjusting the volume) play audio from a youtube video. Haven't futzed with jack detection yet.

The two things I changed were adopting the `boot.kernelPackages = pkgs.linuxPackages_latest;` from your knedlsepp/flakebook and changing the way the /lib/firmware/dfw_sst.bin is created/overridden.

**Comment by knedlsepp** [comment]
Are you using the 19.03 channel or the new 19.09?

**Comment by joseph-long** [comment]
Installed from nixos-graphical-19.03.173522.021d733ea3f-x86_64-linux.iso today

**Comment by joseph-long** [comment]
After a sleep/wake cycle, I think maybe pulseaudio got out of sync and thought it was on the headphone profile. So, there's still work to be done. I think the galliumos scripts show how to run pactl as a user.

**Comment by knedlsepp** [comment]
Thx for all your help on this. Finally got sleep + audio + jack-detection (somewhat) working since: https://github.com/knedlsepp/flakebook/commit/c9f02343afd0d069c732026169b801b9c7fdeb70
Using NixOS-19.09 + Full ROM / UEFI (MrChromebox-4.10 09/05/2019)
